uwsgi: 
  pythonpath   : /usr/local/lib/python2.7/dist-packages/
  pythonpath   : /root/projects/myway/
  socket       : /tmp/uwsgi-myway.sock
  chmod-socket : 666
  callable     : app
  master       : true
  module       : manager
  workers      : 4
  threads      : 10
  idle         : 1800
  touch-reload : /root/projects/myway
  logto        : /root/projects/myway/log/uwsgi.log
  static-map   : /static=/root/projects/myway/myway/static
